---
# tasks file for Docker
- name: Install Docker
  become: yes
  package:
    name: docker
    state: present
  notify: Restart Docker Service

- name: start and enable docker
  become: yes
  service: 
    name: docker
    state: started
    enabled: yes

- name: create docker compose  directory
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'
  become: yes

- name: get the latest docker compose version 
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: yes
  register: docker_compose_latest

- name: Set the docker compose version
  set_fact:
    docker_compose_version: "{{ docker_compose_latest.json.tag_name }}"

- name: Install docker compose plugins
  get_url: 
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: "0755"
  become: yes

- name: create docker group
  group:
    name: docker
    state: present

- name: add user to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

# - name: Run Docker compose file on remote
#   community.docker.docker_compose_v2:
#     project_src: /opt/todo-app
#     state: present
#   become: yes

- name: List contents of /opt/todo-app
  become: yes
  command: ls -l
  args:
    chdir: /opt/todo-app

- name: runnig compose file
  become: yes 
  command: "docker compose up -d"
  args: 
    chdir: /opt/todo-app








