name: Provision of ec2 instance

on:
 push:
  branch:
   - main

jobs:
 provision_of_ec2:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout the repository
     uses: actions/checkout@v4
   
   - name: Install python version 
     uses: actions/setup-python@v2
     with:
      python-version: "3.10"
   
   - name: install the packages
     run: |
      python -m pip install --upgrade pip
      pip install ansible boto3
      ansible-galaxy collection install amazon.aws
    
   - name: Configure Aws credentilas
     uses:  aws-actions/configure-aws-credentials@v1
     with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      aws-region: ap-south-1
      
   
   - name: Generate SSH key
     run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
      chmod 600 ~/.ssh/ec2_key.pem
   
   - name: Debug the SSH key
     run:
      ls -l ~/.ssh/ec2_key.pem
   
   - name: Run the ansible playbook
     run: |
      ansible-playbook ansible/playbooks/provision_and_config.yml \
      -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem"
   
  
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    EC2_SSH_PRIVATE_KEY: ~/.ssh/ec2_key.pem
    SECRET: ${{ secrets.SECRET }} 
    ANSIBLE_HOST_KEY_CHECKING: False



